// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBMdjW5DD8BfRZ96MuMYUqEk-dAZw2Fgc',
    appId: '1:880235945136:web:adb87067218620852caf75',
    messagingSenderId: '880235945136',
    projectId: 'fir-signup-cb5c2',
    authDomain: 'fir-signup-cb5c2.firebaseapp.com',
    storageBucket: 'fir-signup-cb5c2.firebasestorage.app',
    measurementId: 'G-9GT5WYHFCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2a_zgLWnl7smmFmC5-ONbuxDsuKr95U0',
    appId: '1:880235945136:android:7b4d591ee68253f02caf75',
    messagingSenderId: '880235945136',
    projectId: 'fir-signup-cb5c2',
    storageBucket: 'fir-signup-cb5c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtSzORTzTJ20305z706-hhrVqjm_C3sQg',
    appId: '1:880235945136:ios:6dbdd1240550a7c02caf75',
    messagingSenderId: '880235945136',
    projectId: 'fir-signup-cb5c2',
    storageBucket: 'fir-signup-cb5c2.firebasestorage.app',
    iosClientId: '880235945136-v7e0c3mm8ugl9ibbd1vhfiuid8527s3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.authetication1st',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtSzORTzTJ20305z706-hhrVqjm_C3sQg',
    appId: '1:880235945136:ios:6dbdd1240550a7c02caf75',
    messagingSenderId: '880235945136',
    projectId: 'fir-signup-cb5c2',
    storageBucket: 'fir-signup-cb5c2.firebasestorage.app',
    iosClientId: '880235945136-v7e0c3mm8ugl9ibbd1vhfiuid8527s3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.authetication1st',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBMdjW5DD8BfRZ96MuMYUqEk-dAZw2Fgc',
    appId: '1:880235945136:web:7f1df4796e00ee8d2caf75',
    messagingSenderId: '880235945136',
    projectId: 'fir-signup-cb5c2',
    authDomain: 'fir-signup-cb5c2.firebaseapp.com',
    storageBucket: 'fir-signup-cb5c2.firebasestorage.app',
    measurementId: 'G-X1KHHWWGKE',
  );
}
